### ISSUE TITLE
是否会考虑支持ReplicatedCollapsingMergeTree？

### ISSUE THREAD

**Issue by xp880906** [tal-tech/cds#17]
开发组成员们，你们好。
在研究本项目的时候产生了一个疑问，希望能得到解答。
背景：在Galaxy生成的Clichouse DDL中，为每个表建立了”ck_is_delete“列，复制表的引擎选用：ReplicatedMergeTree。
问题：这里为什么没有选用ReplicatedCollapsingMergeTree作为复制表的引擎，使用”sign“代替”ck_is_delete“？

望解答

**Comment by org0000h** [comment]
选用ReplicatedCollapsingMergeTree作为复制表的引擎，使用”sign“代替”ck_is_delete“理论上是可以的，但是由于历史数据还在，所以查询时要合并大量条目，速度并不理想。不过ReplicatedCollapsingMergeTree可以回溯历史，这点挺好的。
关于建表方案参考这里https://gocn.vip/topics/11306

**Comment by xp880906** [comment]
> 选用ReplicatedCollapsingMergeTree作为复制表的引擎，使用”sign“代替”ck_is_delete“理论上是可以的，但是有可能数据会无序 插入clickhouse，导致基于sign的合并出现问题，而且要求写入数据的程序记住对象的状态，以便能够将其取消。
> 关于建表方案参考这里https://gocn.vip/topics/11306

您好，文章我看了，写得很好！
在我使用的最新版本中，CDS默认生成的DDL，使用的是MergeTree，如果想要得到Update数据的支持，手动改成ReplacingMergeTree就可以了吧？
*另外，顺带吐槽一下Clickhouse，ReplacingMergeTree我之前测试过，Merge之后还不能保证没有重复的数据，这也增加了我们查询数据时的难度。。。*

最后，关于CollapsingMergeTree乱序插入导致的问题，是否可以通过VersionedCollapsingMergeTree来解决（Clickhouse的表引擎真的是想吐槽。。。）？

**Comment by org0000h** [comment]
如果想要得到Update数据的支持，手动改成ReplacingMergeTree就可以。
VersionedCollapsingMergeTree可以解决乱序问题，但是要求写入数据的程序应记住对象的状态。ReplacingMergeTree则不需要管理。
