### ISSUE TITLE
mysql 的 binlog 实时解析,没有看到,你们这个同步工具,有没有做mysql binlog实时同步??

### ISSUE THREAD

**Issue by ithjz** [tal-tech/cds#31]
mysql 的 binlog 实时解析,没有看到,你们这个同步工具,有没有做mysql binlog实时同步??

我全文搜索了 binlog ,没有发现binlog这个插件,请问你们实现了binlog解析吗?

**Comment by org0000h** [comment]
通过canal https://github.com/alibaba/canal实现的binlog同步至kafka
