### ISSUE TITLE
亿级表全量同步效率如何

### ISSUE THREAD

**Issue by warrenwx** [tal-tech/cds#6]

**Comment by zxc111** [comment]
@warrenwx 主要受限于 Clickhouse 资源（磁盘io）使用情况，例如白天高频使用时，插入性能差，整体耗时就会比较久，夜间都是离线任务，资源使用较少，插入相比白天会有几倍甚至几十倍的差距

**Comment by warrenwx** [comment]
谢谢回复，其实我更加关注从数据源拉取全量数据的效率，因为一般来说存量的数据都是巨大的。
