### ISSUE TITLE
请问源端的update是如何处理的?

### ISSUE THREAD

**Issue by Fanduzi** [tal-tech/cds#88]
是使用这种方式吗 https://mp.weixin.qq.com/s/a8OfsBn9VFnj7oxp0IIVGg
ReplacingMergeTree + 视图(argMax)?

**Comment by Fanduzi** [comment]
还想问一下, 初始化数据全量同步是类似使用逻辑备份的方式吗? RR界别开事务获取binlog file pos gtid然后通过MVCC查询数据写入clickhouse, 增量是根据之前记录的binlog file pos gtid消费过滤canal拿过来的binlog?

**Comment by Fanduzi** [comment]
对于OLTP数据库 DML可能是频繁地小事务, clickhouse建议batch insert, 避免too many part合并不过来, 咱们这边对源端产生的语句转换为INSERT后有做缓存然后再Batch insert写入clickhouse吗?还是就是源端来1条clickhouse就插一此

**Comment by zxc111** [comment]
> 是使用这种方式吗 https://mp.weixin.qq.com/s/a8OfsBn9VFnj7oxp0IIVGg
> ReplacingMergeTree + 视图(argMax)?

是这样的


> 还想问一下, 初始化数据全量同步是类似使用逻辑备份的方式吗? RR界别开事务获取binlog file pos gtid然后通过MVCC查询数据写入clickhouse, 增量是根据之前记录的binlog file pos gtid消费过滤canal拿过来的binlog?

流程先开启canal的监听，然后从 mysql 拉数据初始化，后续的变更都在 binlog



> 对于OLTP数据库 DML可能是频繁地小事务, clickhouse建议batch insert, 避免too many part合并不过来, 咱们这边对源端产生的语句转换为INSERT后有做缓存然后再Batch insert写入clickhouse吗?还是就是源端来1条clickhouse就插一次
> 比如mysql执行1000个insert , clickhouse是执行1000个insert还是1个insert values1000个?

batch + 时间限制。
clickhouse-go driver batch insert 实现参见 https://github.com/ClickHouse/clickhouse-go/issues/109

**Comment by Fanduzi** [comment]
> > 是使用这种方式吗 https://mp.weixin.qq.com/s/a8OfsBn9VFnj7oxp0IIVGg
> > ReplacingMergeTree + 视图(argMax)?
> 
> 是这样的
> 
> > 还想问一下, 初始化数据全量同步是类似使用逻辑备份的方式吗? RR界别开事务获取binlog file pos gtid然后通过MVCC查询数据写入clickhouse, 增量是根据之前记录的binlog file pos gtid消费过滤canal拿过来的binlog?
> 
> 流程先开启canal的监听，然后从 mysql 拉数据初始化，后续的变更都在 binlog
> 
> > 对于OLTP数据库 DML可能是频繁地小事务, clickhouse建议batch insert, 避免too many part合并不过来, 咱们这边对源端产生的语句转换为INSERT后有做缓存然后再Batch insert写入clickhouse吗?还是就是源端来1条clickhouse就插一次
> > 比如mysql执行1000个insert , clickhouse是执行1000个insert还是1个insert values1000个?
> 
> batch + 时间限制。
> clickhouse-go driver batch insert 实现参见 [ClickHouse/clickhouse-go#109](https://github.com/ClickHouse/clickhouse-go/issues/109)

感谢回复, 1和3已经明白了, 关于第二个问题还想问一下
全量数据拉取完成后, 咱们这边是如果知道从哪个`点`消费binlog做增量呢? 是类似逻辑备份的原理吗
```
FLUSH /*!40101 LOCAL */ TABLES 
' # 对整个实例加全局读锁，如果存在表锁将阻塞加全局读锁语句'

FLUSH TABLES WITH READ LOCK
' #在session级别修改隔离级别为RR'

SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ
'# 开启一个一致性快照事务，必须在隔离级别RR下才能开启一个快照事务'

START TRANSACTION /*!40100 WITH CONSISTENT SNAPSHOT */ 
'#查看是否开启GTID'

SHOW VARIABLES LIKE 'gtid\_mode' 
'#如果开启GTID则查看当前的事务GTID集合'

SELECT @@GLOBAL.GTID_EXECUTED 
'#查看当前数据的binlog pos'

SHOW MASTER STATUS  
'#释放全局读锁'

UNLOCK TABLES 

开始对指定表执行SELECT获取全量数据
```
FTWRL 目的获取binlog file pos 或 GTID. 开启RR级别保证后续所有表的查询结果都是在一个一致性的视图中获取
增量同步时是根据binlog file pos 还是 GTID呢?

**Comment by Fanduzi** [comment]
又想到一个问题, 加入源端修改了表结构, 同步是不是会报错中断呢?

**Comment by org0000h** [comment]
https://github.com/tal-tech/cds/blob/master/doc/CDS%E4%B8%ADClickHouse%E4%BD%BF%E7%94%A8%E7%9A%84%E5%BB%BA%E8%A1%A8%E6%96%B9%E6%A1%88.md
