### ISSUE TITLE
请问支持创建分布式表吗

### ISSUE THREAD

**Issue by Fanduzi** [tal-tech/cds#90]
我这边clickhouse是一个3分片集群, 配置同步任务时clickhouse这边创建的是分布式表还是普通单表啊?

**Comment by zxc111** [comment]
默认建表的结构是
`local(本地表,MergeTree)`->`local_full_all(分布式表)`-> `local_mv(物化视图)` -> `.rtu_inner.local_mv(物化视图实际表,replacingMergeTree)`-> `local_all(分布式表)`->'local_now(视图)'
